#!/usr/bin/env node
// Mock placement fixtures for pre-drop testing.
//
// BMorg embargoes placement until ~1 week before the event, so for most of the
// summer the current year's camp/art locations are null and location-dependent
// features (map pins, addresses, camp outlines) can't be exercised. This script
// fabricates PLAUSIBLE locations from the previous year's real data:
//
//   - camps: matched to last year's camp by normalized name; last year's GPS +
//     address fields are copied, with GPS translated by the delta between the
//     two years' Man (golden spike) coordinates so pins land in the right part
//     of the new city. Unmatched camps stay unplaced (realistic).
//   - art: matched by name the same way; unmatched art gets a random translated
//     location sampled (with jitter) from last year's art GPS cloud.
//   - update.json timestamps are bumped to "now" so the app re-imports the JSON
//     over any previously restored seed (PlayaDB `needsImport`).
//   - a MOCK_LOCATIONS sentinel file is written into APIData.bundle. The iOS
//     test suite, playa-seed, and the deploy workflow all refuse to proceed
//     while it exists, so mock data cannot ship by accident.
//
// Optionally (--map-fixtures) last year's camp_outlines/camp_labels geojson is
// copied into the current year's Map.bundle to exercise the embargo-gated
// boundary layers. (The real files are generated closer to the event by
// scripts/apply_placement.js from the vendored placement drops.)
//
// Usage (from Submodules/iBurn-Data):
//   node scripts/mock_locations.js apply [--map-fixtures] [--year 2026] [--ref-year 2025]
//   node scripts/mock_locations.js revert [--year 2026]
//
// `revert` restores every touched file via git checkout and removes the sentinel.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const args = process.argv.slice(2);
const command = args[0];
function flag(name) { return args.includes(name); }
function opt(name, fallback) {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}

const year = opt('--year', '2026');
const refYear = opt('--ref-year', '2025');
const dataRoot = path.join(__dirname, '..', 'data');
const bundleDir = path.join(dataRoot, year, 'APIData', 'APIData.bundle');
const mapBundleDir = path.join(dataRoot, year, 'Map', 'Map.bundle');
const refBundleDir = path.join(dataRoot, refYear, 'APIData', 'APIData.bundle');
const refMapBundleDir = path.join(dataRoot, refYear, 'Map', 'Map.bundle');
const sentinelPath = path.join(bundleDir, 'MOCK_LOCATIONS');

const SENTINEL_TEXT = `This bundle contains MOCK location data generated by scripts/mock_locations.js
from ${refYear} placement for pre-drop testing. It must never ship.
Revert with: node scripts/mock_locations.js revert --year ${year}
`;

function loadJSON(p) { return JSON.parse(fs.readFileSync(p, 'utf8')); }
function saveJSON(p, obj) { fs.writeFileSync(p, JSON.stringify(obj, null, 2)); }
function normalizeName(name) {
  return (name || '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

function manCoordinate(y) {
  const layout = loadJSON(path.join(dataRoot, y, 'layouts', 'layout.json'));
  return layout.center.geometry.coordinates; // [lon, lat]
}

function apply() {
  const [refLon, refLat] = manCoordinate(refYear);
  const [curLon, curLat] = manCoordinate(year);
  const dLon = curLon - refLon;
  const dLat = curLat - refLat;

  const translate = (loc) => {
    const out = { ...loc };
    if (typeof out.gps_latitude === 'number') out.gps_latitude += dLat;
    if (typeof out.gps_longitude === 'number') out.gps_longitude += dLon;
    return out;
  };

  // Camps: name-match against ref year
  const refCamps = new Map();
  for (const c of loadJSON(path.join(refBundleDir, 'camp.json'))) {
    if (c.location_string && c.location) refCamps.set(normalizeName(c.name), c);
  }
  const camps = loadJSON(path.join(bundleDir, 'camp.json'));
  let campMatched = 0;
  for (const camp of camps) {
    const ref = refCamps.get(normalizeName(camp.name));
    if (!ref) continue;
    camp.location_string = ref.location_string;
    camp.location = translate(ref.location);
    campMatched++;
  }
  saveJSON(path.join(bundleDir, 'camp.json'), camps);

  // Art: name-match, unmatched sampled from the translated ref cloud + jitter
  const refArt = new Map();
  const refArtCloud = [];
  for (const a of loadJSON(path.join(refBundleDir, 'art.json'))) {
    if (a.location && typeof a.location.gps_latitude === 'number') {
      refArt.set(normalizeName(a.name), a);
      refArtCloud.push(a.location);
    }
  }
  const art = loadJSON(path.join(bundleDir, 'art.json'));
  let artMatched = 0, artSampled = 0;
  for (const piece of art) {
    const ref = refArt.get(normalizeName(piece.name));
    if (ref) {
      piece.location_string = ref.location_string;
      piece.location = translate(ref.location);
      artMatched++;
    } else if (refArtCloud.length) {
      const sample = refArtCloud[Math.floor(Math.random() * refArtCloud.length)];
      const jitter = () => (Math.random() - 0.5) * 0.002; // ~±100 m
      piece.location_string = 'Open Playa';
      piece.location = {
        ...translate(sample),
        gps_latitude: translate(sample).gps_latitude + jitter(),
        gps_longitude: translate(sample).gps_longitude + jitter(),
      };
      artSampled++;
    }
  }
  saveJSON(path.join(bundleDir, 'art.json'), art);

  // Bump update.json so the app re-imports JSON over any restored seed.
  // NOTE: no extra marker key here — the legacy Yap importer
  // (BRCDataImporter loadUpdatesFromData:) treats every top-level key as a
  // {file, updated} entry and crashes on anything else. The MOCK_LOCATIONS
  // sentinel file is the canonical marker.
  const updatePath = path.join(bundleDir, 'update.json');
  const update = loadJSON(updatePath);
  // PlayaAPI decodes with strict .iso8601 (no fractional seconds) — strip millis.
  const now = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  for (const key of Object.keys(update)) {
    if (update[key] && typeof update[key] === 'object' && 'updated' in update[key]) {
      update[key].updated = now;
    }
  }
  saveJSON(updatePath, update);

  fs.writeFileSync(sentinelPath, SENTINEL_TEXT);

  if (flag('--map-fixtures')) {
    for (const f of ['camp_outlines.geojson', 'camp_labels.geojson']) {
      fs.copyFileSync(path.join(refMapBundleDir, f), path.join(mapBundleDir, f));
    }
    console.log(`map fixtures: copied ${refYear} camp_outlines/camp_labels into ${year} Map.bundle`);
  }

  console.log(`camps: ${campMatched}/${camps.length} matched to ${refYear} placements`);
  console.log(`art:   ${artMatched}/${art.length} matched, ${artSampled} sampled from the ${refYear} cloud`);
  console.log(`sentinel written: ${path.relative(process.cwd(), sentinelPath)}`);
  console.log('REMEMBER: playa-seed, the iOS tests, and deploy will refuse while the sentinel exists.');
}

function revert() {
  const repoRoot = path.join(__dirname, '..');
  const rel = (p) => path.relative(repoRoot, p);
  execSync(
    `git -C "${repoRoot}" checkout -- ` +
    `"${rel(bundleDir)}" ` +
    `"${rel(path.join(mapBundleDir, 'camp_outlines.geojson'))}" ` +
    `"${rel(path.join(mapBundleDir, 'camp_labels.geojson'))}"`,
    { stdio: 'inherit' }
  );
  if (fs.existsSync(sentinelPath)) fs.unlinkSync(sentinelPath);
  console.log('reverted APIData.bundle + map geojson; sentinel removed');
}

if (command === 'apply') {
  apply();
} else if (command === 'revert') {
  revert();
} else {
  console.error('usage: mock_locations.js <apply|revert> [--map-fixtures] [--year YYYY] [--ref-year YYYY]');
  process.exit(1);
}
